### ISSUE TITLE
Colour animation covering content fix

### ISSUE THREAD

**Issue by siimsams** [hsellik/koderz#1]
I checked your site out. Awesome funnel! I found an issue where the colour animation covers some content. I can't open a PR so I'm sending you the files instead.

### Card.vue
https://pastebin.com/Cpc60kDp
### Contact.vue
https://pastebin.com/kWPxvjfJ
### Footer.vue
https://pastebin.com/R48myA06
### Heading.vue
https://pastebin.com/pdrGB9Ai
### Hero.vue
https://pastebin.com/HEevRk5w

**Comment by hsellik** [comment]
Hi @siimsams ,

It was like this on purpose. However, if it annoys users, perhaps it's a good idea to change the z-index of the content indeed.

Thank you for your contribution!
